### ISSUE TITLE
Fails when keeping bKGD chunks

### ISSUE THREAD

**Issue by haarp** [google/zopfli#97]
Using zopflipng --keepchunks=bKGD on a file with a bKGD chunk consistently results in an error:

    Error: verification of result failed.
    There was an error

Example file:

![panel](https://cloud.githubusercontent.com/assets/781030/13904564/594298fa-eea5-11e5-8305-eb68f22b2143.png)

**Comment by lvandeve** [comment]
I see what happened: zopfli converted the image from RGBA to palette. The PNG spec prescribes a different type of bKGD chunk for RGBA than for palette. For RGBA it can contain a full RGBA color, while for palette just a palette index. And when using --keepchunks it literally keeps the original chunks, it doesn't parse bKGD chunks.

This is an interesting side effect I hadn't thought of, thanks for reporting!

There are several different fixes I can think of:

Discard bKGD chunks anyway in case of a color model change, that would ignore a user request but do best compression.

Or, parse their color, take it into account, and choose only a matching color model or convert the bKGD chunk itself. This may hurt compression because it may e.g. be unable to choose greyscale if the image is grey but the bKGD is set to red.

**Comment by lvandeve** [comment]
It should be fixed now, it keeps original color type when keeping bKGD or sBIT chunks. It is highly recommended to not keep bKGD chunks. For example web browsers do not use it.

The example image in the original post is 444 bytes. When zopflifying without keeping bKGD, the result is 162 bytes. But when keeping bKGD, the result is 394 bytes. That is because it is forced to keep the RGBA color type, rather than using a 3-color palette for this image.

**Comment by haarp** [comment]
Now that was a quick fix! And the chosen solution seems quite reasonable. Thanks!
